"""empty message

Revision ID: 2efea91ea381
Revises: 
Create Date: 2021-07-29 12:43:56.239745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efea91ea381'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('friends_list', sa.Text(), nullable=True))
    op.add_column('userdata', sa.Column('invites', sa.Text(), nullable=True))
    op.drop_column('userdata', 'friend_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('friend_list', sa.TEXT(), nullable=True))
    op.drop_column('userdata', 'invites')
    op.drop_column('userdata', 'friends_list')
    # ### end Alembic commands ###
